server {
    listen 80;
    server_name kei.fahmiefendy.dev localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # Enable gzip compression for better loading performance
    gzip on;
    gzip_types text/plain text/css application/javascript image/svg+xml image/png image/jpeg image/webp;
    gzip_min_length 1000;

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
